GET https://{{host}}/get?source=reqor-demo

###

POST https://{{host}}/post
Content-Type: application/json
X-Request-Id: demo-001
Authorization: Bearer sample-token

{
  "name": "reqor",
  "action": "demo",
  "tags": ["http", "sample"]
}

###

PUT https://{{host}}/put
Content-Type: application/json

{
  "id": "demo-001",
  "status": "updated"
}

###

DELETE https://{{host}}/delete?id=demo-001
